config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists do
    resources :bookmarks, only: [ :new, :create, :destroy ]
    resources :votes, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :list
  validates :content, presence: true
  validates :rating, numericality: { greater_than: 0, less_than_or_equal_to: 5, only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
    @movie = Movie.all
    @movienames = []
    @movie.each do |movie|
      @movienames << [movie.id.to_s, movie.title]
    end
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.save
    @list = List.find(params[:list_id])
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:list_id])
    list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @vote = Vote.new
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save!
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def new
    @vote = Vote.new
    @list = List.find(params[:list_id])
  end

  def create
    @vote = Vote.new(vote_params)
    @vote.save
    @list = List.find(params[:list_id])
    redirect_to list_path(@list)
  end

  private

  def vote_params
    params.require(:vote).permit(:content, :list_id, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
<h1>Add a new bookmark</h1>
<%= simple_form_for [ @list, @bookmark ] do |f|%>
<%= f.input :comment %>
<%= f.input :movie_id, collection:@movienames, label_method: :second, value_method: :first %>
<%= f.input :list_id, :as => :hidden, :input_html => { :value => @list.id } %>
<%= f.submit %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="bannershow mb-2" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path "cinema.jpg", height: 300, crop: :fill %>')">
      <h1 class="p-4">Movie list</h1>
      <h3 class="px-4">Organize your movie lists</h3>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="container">
  <h1>Update list <%= @list.name %></h1>
  <%= simple_form_for(@list) do |f|%>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
  <% end %>
</div>

app/views/lists/index.html.erb
<div class="container">
  <h1>All our Lists (<%= @lists.count %>)</h1>
  <div>
    <% @lists.each do |list| %>
      <div class="card m-2">
        <div class="d-flex justify-content-between pb-2 rounded">
          <div>
            <% link_name = "#{list.name} (#{list.bookmarks.count})"%>
            <%= link_to link_name, list_path(list), class: "m-2" %>
          </div>
          <div>
            <p class="text-warning"><strong>
            <% count_stars = 0 %>
            <% list.votes.each do |vote| %>
            <%   count_stars += vote.rating %>
            <% end %>
            <% if list.votes.count > 0 %>
              <% count_stars /= list.votes.count %>
              <% count_stars.times do %>
                <i class="fa fa-star"></i>
              <% end %>
            <% end %>
            </strong></p>
          </div>
          <div style="min-height: 100px" class="p-2">
            <% if list.photo.attached? %>
              <%= cl_image_tag list.photo.key, height: 100, crop: :fill %>
            <% elsif list.bookmarks.length > 0 %>
              <img src="<%= list.bookmarks.first.movie.poster_url %>" alt="<%= list.bookmarks.first.movie.title %> img" style="height: 100px">
            <% else %>
              <div class="w25">
                Empty.
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="m-2">
    <%= link_to "New list", new_list_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f|%>
<%= f.input :name %>
<%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="container">
  <% if @list.photo.attached? %>
    <div class="bannershow" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">
      <h1><%= @list.name %></h1>
    </div>
  <% else %>
    <h1><%= @list.name %></h1>
  <% end %>
  <h2>Bookmarks</h2>
  <% if @list.bookmarks.size > 0 %>
    <div class="row row-cols-4">
      <% @list.bookmarks.each do |bookmark| %>
          <div class="card col m-2 bg-secondary">
            <h4 class="text-white p-2" style="font-size: 18px;"><%= bookmark.movie.title %></h4>
            <hr>
            <div class="d-flex">
              <div class="w-25">
                  <img src="<%= bookmark.movie.poster_url %>" alt="<%= bookmark.movie.title %> img" class="w-100">
              </div>
              <div class="w-75 px-2">
                <p class="text-white" style="font-size: 10px;"><%= bookmark.movie.overview %></p>
              </div>
            </div>
            <div class="d-flex justify-content-between pb-2 rounded">
              <div>
                <h5 class="text-white" style="font-size: 18px;"><%= bookmark.comment %></h5>
              </div>
              <div>
                <%= link_to "Remove", list_bookmark_path(bookmark), method: :delete, class: "btn btn-danger text-white", style: "font-size: 12px;" %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  <% else %>
    <p>No bookmarks available.</p>
  <% end %>
  <div class="mt-3">
    <%= link_to "Add bookmark", new_list_bookmark_path(@list), class: "btn btn-primary", style: "font-size: 12px;" %>
    <%= link_to "Edit list", edit_list_path(@list), class: "btn btn-primary", style: "font-size: 12px;" %>
    <%= link_to "All lists", root_path, class: "btn btn-primary", style: "font-size: 12px;" %>
  </div>
  <hr>
  <h2>Reviews:</h2>
  <% if @list.votes.size > 0 %>
    <% @list.votes.each do |vote| %>
      <div class="card pt-3 m-2">
        <div class="d-flex">
          <div class="px-2">
            <p ><strong>Rating</strong>:</p>
          </div>
          <div>
            <p class="text-warning">
              <% vote.rating.times do %>
                <i class="fa fa-star"></i>
              <% end %>
            </p>
          </div>
        </div>
        <p class="px-2"><strong>Comment</strong>: <%= vote.content %></p>
      </div>
    <% end %>
  <% else %>
    <p>No review available.</p>
  <% end %>
  <div class="mt-3">
    <%= link_to "Add review", new_list_vote_path(@list), class: "btn btn-primary m-2", style: "font-size: 12px;" %>
  </div>
</div>

app/views/votes/new.html.erb
<div class="container">
<h1>Add a new review</h1>
<%= simple_form_for [ @list, @vote ] do |f|%>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.input :list_id, :as => :hidden, :input_html => { :value => @list.id } %>
<%= f.submit %>
<% end %>
</div>